import type { ExerciseDefinition } from '../core/types';
export const EXERCISES:ExerciseDefinition[]=[
 {id:'warmup-voice',title:'Wake the Instrument',category:'warmup',description:'Articulation, breath, pitch and rhythmic mouth movement. Get the instrument online before asking it to improvise.',skills:[{skill:'articulation',weight:1},{skill:'breath',weight:.8},{skill:'pitch',weight:.45}],durationSeconds:120,difficulty:1,constraints:[{kind:'delivery_changes',value:4}],promptStrategy:'none',successCriteria:['clean consonants','four delivery changes','steady breath'],tags:['warmup','voice']},
 {id:'rhyme-burst',title:'Rhyme Burst',category:'rhyme',description:'Generate a family fast enough that your mouth can use it before your analytical brain catches up.',skills:[{skill:'rhyme_retrieval',weight:1},{skill:'vocabulary',weight:.55}],durationSeconds:150,difficulty:2,constraints:[{kind:'rhyme_count',value:12}],promptStrategy:'word',successCriteria:['12 distinct rhyme candidates','use at least 6 in bars'],tags:['rhyme']},
 {id:'multi-chain',title:'Multisyllabic Chain',category:'rhyme',description:'Build multi-syllable sound families, then keep meaning moving while the sound pattern stays alive.',skills:[{skill:'multisyllabic_rhyme',weight:1},{skill:'internal_rhyme',weight:.7},{skill:'coherence',weight:.35}],durationSeconds:210,difficulty:5,constraints:[{kind:'multis',value:5},{kind:'internal_target',value:3}],promptStrategy:'word',successCriteria:['five multi-syllable families','three internal chains','coherent thought'],tags:['rhyme','advanced']},
 {id:'pocket-switch',title:'Pocket Switch',category:'flow',description:'Change cadence every four bars without abandoning the pulse. Treat delivery like drum vocabulary.',skills:[{skill:'pocket',weight:.9},{skill:'flow_variation',weight:1},{skill:'rhythm',weight:.8}],durationSeconds:240,difficulty:5,constraints:[{kind:'flow_change_bars',value:4},{kind:'flow_modes',value:4}],promptStrategy:'none',successCriteria:['four distinct cadence states','stays in time','no reset between switches'],tags:['flow']},
 {id:'topic-whiplash',title:'Topic Whiplash',category:'transition',description:'Change the subject while preserving momentum, rhyme and identity. The subject changes; the engine does not.',skills:[{skill:'topic_transition',weight:1},{skill:'recovery',weight:.7},{skill:'coherence',weight:.8}],durationSeconds:240,difficulty:7,constraints:[{kind:'topic_change_bars',value:2},{kind:'no_stop'}],promptStrategy:'topic',successCriteria:['six transitions','no reset','callback one earlier topic'],tags:['transfer','transition']},
 {id:'observation',title:'Field Observation',category:'observation',description:'Rap only about what is actually around you. Concrete nouns first; meaning second.',skills:[{skill:'observation',weight:1},{skill:'association',weight:.75},{skill:'imagery',weight:.75}],durationSeconds:240,difficulty:4,constraints:[{kind:'environment_only'},{kind:'concrete_nouns',value:10}],promptStrategy:'none',successCriteria:['ten concrete observations','three sensory details','one surprising association'],tags:['observation']},
 {id:'story-triad',title:'Character / Place / Object',category:'story',description:'Fuse three unrelated ingredients into a story with a change, escalation and earned ending.',skills:[{skill:'storytelling',weight:1},{skill:'imagery',weight:.75},{skill:'coherence',weight:.9},{skill:'association',weight:.5}],durationSeconds:300,difficulty:6,constraints:[{kind:'ingredients',value:3},{kind:'ending_callback'}],promptStrategy:'scene',successCriteria:['setup','change','escalation','callback ending'],tags:['story']},
 {id:'wordplay-lab',title:'Meaning Flip',category:'wordplay',description:'Take one phrase and force it through literal, metaphorical, double-meaning, absurd and reversal lenses.',skills:[{skill:'wordplay',weight:1},{skill:'metaphor',weight:.9},{skill:'punchlines',weight:.8}],durationSeconds:240,difficulty:6,constraints:[{kind:'interpretations',value:5},{kind:'reversal'}],promptStrategy:'word',successCriteria:['five distinct interpretations','one clean setup/payoff','one unexpected turn'],tags:['wordplay']},
 {id:'voice-dynamics',title:'Voice Dynamics',category:'voice',description:'Run the same idea through contrasting pitch, volume, texture, articulation and melodic delivery.',skills:[{skill:'vocal_dynamics',weight:1},{skill:'pitch',weight:.7},{skill:'articulation',weight:.6}],durationSeconds:180,difficulty:3,constraints:[{kind:'delivery_changes',value:6}],promptStrategy:'topic',successCriteria:['six deliberate delivery changes','intelligibility survives'],tags:['voice']},
 {id:'never-stop',title:"Don't Fucking Stop",category:'recovery',description:'Continuous improvisation. A mistake is raw material. A pause is an invitation. A dead end becomes the next image.',skills:[{skill:'recovery',weight:1},{skill:'pocket',weight:.55},{skill:'coherence',weight:.6}],durationSeconds:210,difficulty:7,constraints:[{kind:'no_stop'},{kind:'random_interruptions',value:6}],promptStrategy:'random',successCriteria:['continuous performance','recover from every interruption','one callback'],tags:['recovery']},
 {id:'open-freestyle',title:'Open Freestyle',category:'open',description:'No special constraint. Make something you actually like. This is your laboratory, not a test.',skills:[{skill:'pocket',weight:.55},{skill:'storytelling',weight:.45},{skill:'wordplay',weight:.45},{skill:'vocal_dynamics',weight:.35},{skill:'coherence',weight:.45}],durationSeconds:300,difficulty:5,constraints:[],promptStrategy:'none',successCriteria:['finish','self-assess honestly','save one moment worth remembering'],tags:['open']},
 {id:'transfer-boss',title:'Transfer Test',category:'gauntlet',description:"Combine the day's weakness with one strength. Four constraints, one uninterrupted performance.",skills:[{skill:'recovery',weight:.7},{skill:'coherence',weight:.8},{skill:'pocket',weight:.7}],durationSeconds:180,difficulty:9,constraints:[{kind:'topic_change_bars',value:2},{kind:'flow_change_bars',value:4},{kind:'no_stop'},{kind:'callback'}],promptStrategy:'random',successCriteria:['all constraints survive','no reset','clean callback ending'],tags:['gauntlet','boss']}
];
