import type { AudioAnalysis, ExerciseDefinition, FailureMode, MetricReceipt, SessionAnalysis, SkillId, Transcript } from './types';
import { analyzePhonology, tokenize, type PhonemeMap } from './phonology';
const FILLERS=new Set(['uh','um','uhh','umm','yeah','like','basically','actually','literally','you','know','so','okay','right']);
const STOP=new Set('the a an and or but to of in on for is it i you my me that this with as at be was are we they he she aint am do did does from into your our their have has had'.split(' '));
const clamp=(n:number,min=0,max=1)=>Math.max(min,Math.min(max,n));
const vowelGroups=(w:string)=>Math.max(1,w.toLowerCase().match(/[aeiouy]+/g)?.length??1);
function syllables(ws:string[]){return ws.reduce((n,w)=>n+vowelGroups(w),0);}
function failureModes(a:{fillerRate:number,maxPause:number,rhymeDensity:number,uniqueWordRatio:number,promptHitRate:number,wordCount:number,wordsPerBar:number|null,audioSilence:number,audioTiming:number|null},exercise?:ExerciseDefinition):FailureMode[]{const out:FailureMode[]=[];if(a.fillerRate>.08)out.push({id:'filler-loop',label:'Filler loop',description:'Filler words are taking a noticeable share of the performance.',severity:clamp((a.fillerRate-.06)*5),evidenceCount:1,lastSeenAt:null,relatedSkills:['recovery','coherence','articulation']});if(a.maxPause>1.8||a.audioSilence>.32)out.push({id:'long-recovery',label:'Long recovery gaps',description:'Silence is becoming a reset instead of a generative opening.',severity:clamp(Math.max(a.maxPause>1.2?(a.maxPause-1.2)/3:0,(a.audioSilence-.2)*2.5)),evidenceCount:1,lastSeenAt:null,relatedSkills:['recovery','pocket','coherence']});if(a.rhymeDensity<.16&&a.wordCount>35)out.push({id:'low-rhyme-density',label:'Low rhyme density',description:'The sample is drifting toward prose-like language under pressure.',severity:clamp(.42-a.rhymeDensity),evidenceCount:1,lastSeenAt:null,relatedSkills:['rhyme_retrieval','internal_rhyme']});if(a.uniqueWordRatio<.4&&a.wordCount>45)out.push({id:'lexical-repetition',label:'Lexical repetition',description:'The active vocabulary is narrowing inside the performance.',severity:clamp(.48-a.uniqueWordRatio),evidenceCount:1,lastSeenAt:null,relatedSkills:['vocabulary','association']});if(exercise?.promptStrategy!=='none'&&a.promptHitRate<.42)out.push({id:'constraint-drift',label:'Constraint drift',description:'The prompt is not surviving into language reliably.',severity:clamp(.62-a.promptHitRate),evidenceCount:1,lastSeenAt:null,relatedSkills:['association','coherence','topic_transition']});if(a.wordsPerBar!==null&&a.wordsPerBar<3)out.push({id:'under-density',label:'Under-dense pocket',description:'Phrase density is light for the current task.',severity:clamp((3-a.wordsPerBar)/3),evidenceCount:1,lastSeenAt:null,relatedSkills:['pocket','rhythm','flow_variation']});if(a.audioTiming!==null&&a.audioTiming>110)out.push({id:'timing-drift',label:'Timing drift',description:'Onsets are frequently far from the selected beat grid.',severity:clamp((a.audioTiming-70)/180),evidenceCount:1,lastSeenAt:null,relatedSkills:['pocket','rhythm','flow_variation']});return out;}
export function analyzeTranscript(transcript:Transcript,durationSeconds:number,promptEvents=0,prompts:string[]=[],exercise?:ExerciseDefinition,audio?:AudioAnalysis,phonemeMap?:PhonemeMap):SessionAnalysis{
  const words=tokenize(transcript.text);const count=words.length;const map=new Map<string,number>();for(const w of words)map.set(w,(map.get(w)??0)+1);const repeatedWords=[...map.entries()].filter(([w,c])=>c>=4&&!STOP.has(w)).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([word,count])=>({word,count}));const fillerCount=words.filter(w=>FILLERS.has(w)).length;const minutes=Math.max(durationSeconds/60,.001);const uniqueWordRatio=map.size/Math.max(count,1);const phon=analyzePhonology(words,phonemeMap);const syllableEstimate=syllables(words);const estimatedBars=Math.max(1,Math.floor(syllableEstimate/12));const wordsPerBar=count/Math.max(1,estimatedBars);
  const promptMetrics=prompts.filter(Boolean).map(prompt=>{const p=tokenize(prompt).filter(w=>w.length>2);const hits=p.filter(x=>words.includes(x)).length;return{prompt,hits:hits>=Math.max(1,Math.ceil(p.length*.35)),confidence:p.length?hits/p.length:0};});const hitCount=promptMetrics.filter(x=>x.hits).length;const promptHitRate=promptMetrics.length?hitCount/promptMetrics.length:(promptEvents?1:0);const pauseRate=audio?.silenceRate??0;const maxPauseSeconds=audio?.maxSilenceSeconds??0;
  const constraintAdherence=clamp(promptHitRate*.45+(1-(audio?.silenceRate??.4))*.2+(audio?.beatAlignment??.5)*.2+(1-fillerCount/Math.max(1,count))*.15);const transferReadiness=clamp((promptHitRate*.3)+(uniqueWordRatio*.25)+(1-fillerCount/Math.max(1,count))*.2+(audio?.beatAlignment??.5)*.15+(phon.rhymeChainScore*.1));
  const inferredSkillScores:Partial<Record<SkillId,number>>={rhyme_retrieval:clamp(.16+phon.rhymeChainScore*.9),internal_rhyme:clamp(.1+phon.internalRhymeRate*.95),multisyllabic_rhyme:clamp(.08+phon.multisyllabicRate*.98),vocabulary:clamp(uniqueWordRatio*1.1),coherence:clamp(.3+promptHitRate*.25+(1-fillerCount/Math.max(1,count))*.35+uniqueWordRatio*.1),association:clamp(.25+promptHitRate*.45+uniqueWordRatio*.25),recovery:clamp(.3+(1-pauseRate)*.3+(audio?1-audio.silenceRate:.5)*.2),pocket:clamp((audio?.beatAlignment??.5)*.55+Math.min(.85,wordsPerBar/8)*.25+(1-fillerCount/Math.max(1,count))*.2),flow_variation:clamp((audio?.dynamicRangeDb??8)/30*.25+(audio?.pitchRangeSemitones??4)/20*.2+(audio?.beatAlignment??.5)*.55),rhythm:clamp((audio?.beatAlignment??.5)*.7+(audio?.onsetRate?Math.min(1,audio.onsetRate/3):.3)*.3),observation:exercise?.category==='observation'?clamp(.25+uniqueWordRatio*.75):undefined,storytelling:exercise?.category==='story'?clamp(.25+promptHitRate*.25+uniqueWordRatio*.2+(1-pauseRate)*.3+(audio?.phraseCount?Math.min(.2,audio.phraseCount/12*.2):0)):undefined,wordplay:exercise?.category==='wordplay'?clamp(.3+phon.internalRhymeRate*.25+phon.rhymeChainScore*.2+uniqueWordRatio*.25):undefined,metaphor:exercise?.category==='story'||exercise?.category==='wordplay'?clamp(.3+uniqueWordRatio*.35+promptHitRate*.25):undefined,topic_transition:exercise?.category==='transition'||exercise?.category==='gauntlet'?constraintAdherence:undefined,articulation:clamp(.35+(audio?.voicedRate??.45)*.4+(1-(audio?.clipRate??0))*.25),breath:clamp(.35+(audio?1-audio.silenceRate:.5)*.35+(audio?.phraseCount?Math.min(.3,audio.phraseCount/10):.15)),pitch:clamp(.25+(audio?.pitchRangeSemitones??3)/16*.75),vocal_dynamics:clamp(.25+(audio?.dynamicRangeDb??6)/24*.75),imagery:exercise?.category==='observation'||exercise?.category==='story'?clamp(.3+uniqueWordRatio*.4+promptHitRate*.3):undefined,punchlines:exercise?.category==='wordplay'?clamp(.25+phon.rhymeChainScore*.25+uniqueWordRatio*.25+promptHitRate*.25):undefined};
  const failures=failureModes({fillerRate:fillerCount/Math.max(1,count),maxPause:maxPauseSeconds,rhymeDensity:phon.rhymeChainScore,uniqueWordRatio,promptHitRate,wordCount:count,wordsPerBar,audioSilence:pauseRate,audioTiming:audio?.timingStdMs??null},exercise);
  const metrics:MetricReceipt[]=[
    {key:'wpm',label:'Speech rate',value:count/minutes,unit:'WPM',evidence:`${count} recognized words across ${durationSeconds.toFixed(1)} seconds.`,confidence:transcript.provider==='web-speech'?.78:.28},
    {key:'lexical',label:'Vocabulary diversity',value:uniqueWordRatio,evidence:`${map.size} unique tokens / ${count||1} total tokens.`,confidence:.9},
    {key:'phonetic',label:'Phonetic patterning',value:phon.rhymeChainScore,evidence:`${phon.rhymeLinks} local links; max chain ${phon.maxChain}.`,confidence:phonemeMap?.size?Math.min(.98,.82+(phon.phonemeCoverage*.16)):.48},
    {key:'internal',label:'Internal rhyme',value:phon.internalRhymeRate,evidence:`Phonetic comparison inside four-word windows.`,confidence:.68},
    {key:'filler',label:'Filler rate',value:fillerCount/Math.max(1,count),evidence:`${fillerCount} filler tokens detected.`,confidence:.8},
    {key:'constraint',label:'Constraint adherence',value:constraintAdherence,evidence:`Prompt hits + continuity + timing + filler control.`,confidence:.68},
    ...(audio?[{key:'silence',label:'Silence rate',value:audio.silenceRate,evidence:`${audio.silenceSegments} silence segments; max ${audio.maxSilenceSeconds.toFixed(1)}s.`,confidence:audio.confidence},{key:'beat',label:'Beat alignment',value:audio.beatAlignment??0,evidence:`Onset-to-grid estimate; only meaningful when a BPM was active.`,confidence:audio.beatAlignment===null?.2:.72},{key:'dynamic',label:'Dynamic range',value:clamp(audio.dynamicRangeDb/24),evidence:`${audio.dynamicRangeDb.toFixed(1)} dB between low and high activity bands.`,confidence:.65}]:[])
  ];
  const notes:string[]=[];if(phonemeMap?.size)notes.push(`Phonetic analysis used ${Math.round(phon.phonemeCoverage*100)}% external pronunciation coverage, with local fallback for the rest.`);if(phon.maxChain>=4)notes.push(`Longest phonetic chain: ${phon.maxChain} consecutive linked words.`);if(audio?.timingStdMs!==null&&audio?.timingStdMs!==undefined)notes.push(`Timing spread around the selected grid: ${audio.timingStdMs.toFixed(0)} ms.`);if(uniqueWordRatio>.62&&count>40)notes.push('Vocabulary variety is helping the performance stay generative.');if(promptMetrics.length&&promptHitRate>.8)notes.push('The constraint survived the performance.');
  return{durationSeconds,wordCount:count,speechRateWpm:count?Math.round(count/minutes):null,fillerCount,fillerRate:fillerCount/Math.max(1,count),uniqueWordRatio,repeatedWords,longPauses:audio?.silenceSegments??0,maxPauseSeconds,pauseRate,rhymeDensity:phon.rhymeChainScore,endRhymeRate:phon.endRhymeRate,internalRhymeRate:phon.internalRhymeRate,approximateMultiRate:phon.multisyllabicRate,vocabularyRichness:uniqueWordRatio,promptHits:hitCount,promptHitRate,promptMetrics,averageConfidence:transcript.words.length?transcript.words.filter(w=>w.confidence!==undefined).reduce((n,w)=>n+(w.confidence??0),0)/Math.max(1,transcript.words.filter(w=>w.confidence!==undefined).length):null,syllableEstimate,estimatedBars,wordsPerBar,metrics,inferredSkillScores,failureModes:failures,notes,phonetic:phon,audio,constraintAdherence,transferReadiness};
}
export function blendSelfAssessment(analysis:SessionAnalysis,assessment:{energy:number;coherence:number;pocket:number;novelty:number}):Partial<Record<SkillId,number>>{return{coherence:(analysis.inferredSkillScores.coherence??.4)*.55+assessment.coherence*.45,pocket:(analysis.inferredSkillScores.pocket??.4)*.55+assessment.pocket*.45,vocal_dynamics:(analysis.inferredSkillScores.vocal_dynamics??.4)*.55+assessment.energy*.45,association:(analysis.inferredSkillScores.association??.4)*.7+assessment.novelty*.3};}
