import type { ExerciseDefinition, SkillId, TrainingProfile } from './types';
import { EXERCISES } from '../content/exercises';
import { ALL_SKILLS } from './types';

export const CALIBRATION:ExerciseDefinition[]=[
  {id:'cal-rhyme',title:'Rhyme Reflex Baseline',category:'calibration',description:'Thirty seconds of rapid rhyme retrieval, then immediately use the family in bars.',skills:[{skill:'rhyme_retrieval',weight:1},{skill:'vocabulary',weight:.4}],durationSeconds:60,difficulty:3,constraints:[{kind:'rhyme_count',value:8}],promptStrategy:'word',successCriteria:['retrieve quickly','use the material'],calibration:true},
  {id:'cal-pocket',title:'Pocket Baseline',category:'calibration',description:'Stay on a steady pulse for one minute. Change cadence once without stopping.',skills:[{skill:'pocket',weight:1},{skill:'rhythm',weight:.9},{skill:'flow_variation',weight:.6}],durationSeconds:60,difficulty:3,constraints:[{kind:'one_flow_change'}],promptStrategy:'none',successCriteria:['stay in pulse','one clean transition'],calibration:true},
  {id:'cal-story',title:'Story Baseline',category:'calibration',description:'Tell a real story with a beginning, change and ending. Rhymes are optional.',skills:[{skill:'storytelling',weight:1},{skill:'coherence',weight:1},{skill:'imagery',weight:.5}],durationSeconds:90,difficulty:4,constraints:[{kind:'beginning_change_ending'}],promptStrategy:'topic',successCriteria:['setup','change','ending'],calibration:true},
  {id:'cal-observe',title:'Observation Baseline',category:'calibration',description:'Use only things you can see or hear right now. Make three association jumps.',skills:[{skill:'observation',weight:1},{skill:'association',weight:.9},{skill:'imagery',weight:.7}],durationSeconds:75,difficulty:4,constraints:[{kind:'environment_only'}],promptStrategy:'none',successCriteria:['concrete details','three associations'],calibration:true},
  {id:'cal-recovery',title:'Recovery Baseline',category:'calibration',description:'Improvise continuously. At three random moments, the prompt changes abruptly.',skills:[{skill:'recovery',weight:1},{skill:'topic_transition',weight:.7},{skill:'coherence',weight:.6}],durationSeconds:90,difficulty:5,constraints:[{kind:'random_interruptions',value:3},{kind:'no_stop'}],promptStrategy:'random',successCriteria:['recover without stopping'],calibration:true},
  {id:'cal-voice',title:'Voice Baseline',category:'calibration',description:'Deliver one idea six ways: pitch, volume, texture, articulation and melodic contour.',skills:[{skill:'vocal_dynamics',weight:1},{skill:'pitch',weight:.8},{skill:'articulation',weight:.7}],durationSeconds:75,difficulty:3,constraints:[{kind:'delivery_changes',value:6}],promptStrategy:'topic',successCriteria:['six distinct deliveries','intelligible'],calibration:true},
  {id:'cal-wordplay',title:'Wordplay Baseline',category:'calibration',description:'Take one word through literal, metaphor, double meaning, absurdity and reversal.',skills:[{skill:'wordplay',weight:1},{skill:'metaphor',weight:.9},{skill:'punchlines',weight:.7}],durationSeconds:75,difficulty:5,constraints:[{kind:'interpretations',value:5}],promptStrategy:'word',successCriteria:['five interpretations'],calibration:true},
  {id:'cal-transfer',title:'Transfer Baseline',category:'calibration',description:'Combine a changing topic with one deliberate flow change and an ending callback.',skills:[{skill:'topic_transition',weight:.8},{skill:'flow_variation',weight:.8},{skill:'recovery',weight:.9},{skill:'coherence',weight:.7}],durationSeconds:120,difficulty:7,constraints:[{kind:'flow_change_bars',value:4},{kind:'topic_change_bars',value:2},{kind:'callback'}],promptStrategy:'random',successCriteria:['combine skills without reset'],calibration:true}
];

export function nextCalibrationExercise(profile:TrainingProfile){return CALIBRATION[profile.calibration.batteryIndex]??null;}
export function calibrationComplete(profile:TrainingProfile){return profile.calibration.completed;}
export function calibrationScoreMap(exercise:ExerciseDefinition,skillScores:Partial<Record<SkillId,number>>){const out:Partial<Record<SkillId,number>>={};for(const s of exercise.skills)if(skillScores[s.skill]!==undefined)out[s.skill]=skillScores[s.skill];return out;}
