import { EXERCISES } from '../content/exercises';
import { INTERRUPTION_WORDS, SCENES, TOPICS, WORDS } from '../content/prompts';
import { chooseFocus, complexityBudget, dependencyDiagnosis, transferCandidate } from './curriculum';
import { skillLabel } from './types';
import { SeededRandom } from './rng';
import type { ExerciseDefinition, SkillId, TrainingProfile, Workout } from './types';

const DAY=86400000;
function overdue(last:number|null){return last?Math.min((Date.now()-last)/DAY,7)/7:1;}
function scoreExercise(ex:ExerciseDefinition,profile:TrainingProfile,target:SkillId,used:ExerciseDefinition[]){let score=0;for(const s of ex.skills){const st=profile.skills[s.skill];if(!st)continue;score+=(1-st.confidence)*s.weight*5+overdue(st.lastPracticedAt)*s.weight;if(s.skill===target)score+=4*s.weight;if(st.recentTrend==='down')score+=1.4*s.weight;}if(ex.transferSkills?.includes(target))score+=2.3;score-=profile.recentExerciseIds.includes(ex.id)?0.9:0;if(used.some(u=>u.category===ex.category))score-=1.2;if(profile.trainingLoad.deloadRecommended&&ex.difficulty>6)score-=3;return score;}
function choose(pool:ExerciseDefinition[],profile:TrainingProfile,target:SkillId,used:ExerciseDefinition[],rng:SeededRandom){return rng.pick([...pool].sort((a,b)=>scoreExercise(b,profile,target,used)-scoreExercise(a,profile,target,used)));}
export function generateWorkout(profile:TrainingProfile,seed:string):Workout{
  const rng=new SeededRandom(seed);const target=chooseFocus(profile);const transfer=transferCandidate(profile,target);const budget=complexityBudget(profile);const targetState=profile.skills[target];const roles=['warmup','base','target','transfer','creative','boss'] as const;const chosen:ExerciseDefinition[]=[];
  for(const role of roles){let pool=EXERCISES.filter(e=>!chosen.includes(e));if(role==='warmup')pool=pool.filter(e=>e.category==='warmup');if(role==='base')pool=pool.filter(e=>e.category==='rhyme'||e.category==='flow');if(role==='target')pool=pool.filter(e=>e.skills.some(s=>s.skill===target));if(role==='transfer')pool=pool.filter(e=>e.category==='transition'||e.category==='story'||e.transferSkills?.includes(target));if(role==='creative')pool=pool.filter(e=>e.category==='observation'||e.category==='story'||e.category==='wordplay'||e.category==='open');if(role==='boss')pool=pool.filter(e=>e.category==='gauntlet'||e.id==='never-stop');if(!pool.length)pool=EXERCISES.filter(e=>!chosen.includes(e));chosen.push(choose(pool,profile,target,chosen,rng));}
  const difficulty=Math.min(budget,Math.max(2,Math.round((targetState?.confidence??.2)*10)+2));const blocks=chosen.map((e,i)=>{const bumped=e.difficulty<=difficulty?e:{...e,difficulty};const rationale=i===0?"Prime the instrument and establish today's baseline.":e.skills.some(s=>s.skill===target)?`Primary target: ${skillLabel(target)}.`:e.skills.some(s=>s.skill===transfer)?`Prerequisite/transfer support for ${skillLabel(transfer)}.`:e.category==='gauntlet'?'Prove the skill survives under stacked pressure.':'Build capacity that the target can borrow.';return{...bumped,rationale,targetScore:targetState?.confidence??.2};});
  const duration=blocks.reduce((n,b)=>n+b.durationSeconds,0);const loadScore=blocks.reduce((n,b)=>n+(b.durationSeconds/60)*b.difficulty,0);return{id:`workout_${seed}`,seed,title:'TODAY',focusSkill:target,weakness:skillLabel(target),diagnosis:dependencyDiagnosis(profile,target),durationSeconds:duration,blocks,level:difficulty,loadScore,transferTarget:transfer};
}
export function randomPrompt(kind:'word'|'topic'|'scene'|'random'|'story'|'none',rng=new SeededRandom(String(Date.now()))):string{if(kind==='word')return rng.pick(WORDS);if(kind==='topic')return rng.pick(TOPICS);if(kind==='scene')return rng.pick(SCENES);if(kind==='story')return`${rng.pick(SCENES)} · ${rng.pick(WORDS)}`;if(kind==='random')return rng.pick(INTERRUPTION_WORDS);return '';}
